title: Sorrento Import APS
baseURL: /
params:
  footer:
    content: 'Made by '
    has_nav: true
    has_social: true
    has_subscribe: true
    links:
      - new_window: true
        text: '@francescofusari'
        url: 'https://www.linkedin.com/in/francesco-fusari-711a6b197/'
    logo_img: ''
    nav_title: Products
    social_title: Connect with us
    subscribe_content: Stay up to date with our latest promotions!
    subscribe_title: Subscribe
    tagline: Sorrento Import APS
  header:
    has_nav: true
    logo_img: ''
    title: Sorrento Import Aps
    menu:
      actions:
        - label: Contact us
          url: /signup
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
